src/main/kotlin/app/revanced/cli/MainCommand.kt, src/main/kotlin/app/revanced/cli/Patcher.kt, src/main/kotlin/app/revanced/patch/PatchLoader.kt, src/main/kotlin/app/revanced/patch/Patches.kt, src/main/kotlin/app/revanced/utils/filesystem/FileSystemUtils.kt, src/main/kotlin/app/revanced/utils/signing/Signer.kt
Java 9 changed the default `ClassLoader` to `AppClassLoader`.
This PR creates a new `URLClassLoader` instead of casting the system class loader to `URLClassLoader` and applying reflective operations for adding `URL`s.
That `URLClassLoader` is then used for loading patches.
Furthermore, it explicitly specifies the type `ClassLoader` for the second argument of `FileSystems.newFileSystem` in order to disambiguate that call in newer Java versions.
=> fix: ClassLoader not working with Java 9+

src/main/kotlin/app/revanced/utils/adb/Constants.kt
I'm guessing it was a typo.
This fixes https://github.com/revanced/revanced-cli/issues/12
=> fix: wrong use of variable substitution / typo

src/main/kotlin/app/revanced/cli/Patcher.kt
If resource patching is enabled, ReVanced CLI looks for the first directory entry in the `build` directory of the cache directory and assumes that those directory entries are directories.
While it may always be the case that the first entry is a directory on Windows, this is not always the case on Linux where files may be listed before directories instead of them being ordered alphabetically.
This PR changes that functionality so that only directories are obtained so the first entry is always a directory (if such a directory exists).
=> fix: only accept directories when looking for files in resource patch

src/main/kotlin/app/revanced/utils/adb/Constants.kt
Fix issues of ReVanced not launching after reboot, because of "permission denied". SELinux blocks the access if the file is not "declared" as an APK file.
See conversation on Discord, #support, thread "[root] ReVanced broken on reboot"
=> Added chcon on mount to fix SELinux issues

src/main/kotlin/app/revanced/cli/command/MainCommand.kt, src/main/kotlin/app/revanced/cli/patcher/Patcher.kt, src/main/kotlin/app/revanced/cli/signing/Signing.kt, src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
=> feat: allow listing patches without other parameters

src/main/kotlin/app/revanced/cli/command/MainCommand.kt
Example:
`[available] amoled: Enables pure black theme.`
=> feat: show description when listing patches

.releaserc
to automatically create a release when e.g. a dependency get's updated
related: https://github.com/orgs/revanced/discussions/261#discussioncomment-3027167
=> ci: trigger release on `build` commits

src/main/kotlin/app/revanced/cli/command/MainCommand.kt
Added new --compatibility option to the CLI that will list compatibilities for every patch with packages and list of versions that this patch currently compatible with.
Usage: `java -jar cli.jar --compatibility -b patches.jar`
Result on current version of patches (1.10.4)
```
INFO:      music                    codecs-unlock       5.03.50
INFO:      music         exclusive-audio-playback       5.03.50
INFO:      music             tasteBuilder-remover       5.03.50
INFO:      music           upgrade-button-remover       5.03.50
INFO:      music                  background-play       5.03.50
INFO:    youtube                      general-ads       17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34
INFO:    youtube                        video-ads       17.14.35, 17.17.34, 17.19.36, …
```
=> feat: added new --compatibility option to lists compatibilities

src/main/kotlin/app/revanced/cli/logging/impl/DefaultCliLogger.kt
Implements #62 
Made DefaultCliLogger to log trace, info to stdOut and warn, error to stdErr.
This PR marked as draft because it's kind of "hacky". It's created to decide if we need this feature right now, or it can be implemented later differently (e.g. using different logging backend)
=> feat: DefaultCliLogger now logs to stdOut and stdErr

src/main/kotlin/app/revanced/cli/command/MainCommand.kt, src/main/kotlin/app/revanced/cli/patcher/Patcher.kt, src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
makes all patches excluded by default. useful for patch dev
=> feat: `--exclusive` switch

src/main/kotlin/app/revanced/cli/logging/impl/DefaultCliLogger.kt, src/main/kotlin/app/revanced/cli/logging/impl/FlushingStreamHandler.kt, src/main/kotlin/app/revanced/cli/patcher/logging/impl/PatcherLogger.kt
My implementation of #62  added two loggers where one use StreamHandler with stdout to separate output of different values to different pipes (stdout and stderr).
But it seems that stdout logger wasn't flushed properly. 
This PR should fix it by introducing FlushingStreamHandler which flushes after every log message.
This PR was not yet tested, because currently I can't test it, but I will do so as soon as possible (probably in 24 hours)
=> fix: Log not showing in CLI 

src/main/kotlin/app/revanced/cli/command/MainCommand.kt
"temporal" changed to "temporary"
=> refactor: fixed erroneous word for "temporary" in CLI help.

src/main/kotlin/app/revanced/utils/adb/Constants.kt
Some banking apps already detect the mountpoint of youtube base apk to determine device is rooted. So mount bind from magisk's mirror to trigger magisk unmount and let it hidden along with MagiskHide or hiding modules.
=> fix: mount bind revanced.apk from magisk's mirror

build.gradle.kts, src/main/kotlin/app/revanced/cli/command/MainCommand.kt, src/main/kotlin/app/revanced/cli/patcher/Patcher.kt, src/main/kotlin/app/revanced/utils/OptionsLoader.kt, src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
This PR implements Patch Options for the CLI.
When the CLI is first run, it creates a `options.toml` file containing all Patch Options if the file does not exist. Defaults are added if they don't exist yet. Being able to supply options via CLI is for a future PR.
This file currently looks like this:
```toml
['custom-branding']
appName = "YouTube ReVanced Testing"
appIconPath = "null"
[theme]
theme = "Amoled"
```
I chose TOML because it's the *de-facto standard* for configuration/options. It's also the most straightforward format to edit, and the library I used is lightweight.
Added CLI args:
- `--options custom-options.toml` - use a different options toml file, default `options.toml`
=> feat: Patch Options CLI implementation

src/main/kotlin/app/revanced/utils/adb/Constants.kt
`monkey` has a bug that unlocks orientation-lock. This method is better as it gets the main activity from the package and runs that using `am`
=> Use "am" instead of "monkey" to launch app

src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
This PR uses tracing logs when the compatibility annotation is missing instead of warning about it.
=> feat: trace logs when compatibility annotation is missing

src/main/kotlin/app/revanced/cli/aligning/Aligning.kt, src/main/kotlin/app/revanced/cli/command/MainCommand.kt, src/main/kotlin/app/revanced/cli/patcher/Patcher.kt, src/main/kotlin/app/revanced/utils/signing/align/ZipAligner.kt, src/main/kotlin/app/revanced/utils/signing/align/zip/ZipFile.kt, src/main/kotlin/app/revanced/utils/signing/align/zip/structures/ZipEntry.kt
This PR fixes the issue when writing to a `ZipFile` creates an invalid header entry for `ZipEntry`s. It can be reproduced on an apk file by Twitch.
=> fix: invalid header when writing a `ZipFile`

docs/1_usage.md
_Fix misspelling or typo, or something_
The word "Learn" has been spell as "Lean" which is incorrect.
=> docs: fix misspelling word

gradle/libs.versions.toml
Fixes mounting not working on some devices.
=> chore: bump revanced-library dependency

gradle/libs.versions.toml
As requested: bumping patcher to 19.
Introducing a breaking change; hopefully this won't cause the patches to explode.
=> build(Needs bump): Bump dependencies to support `PatchOption#valueType`

src/main/kotlin/app/revanced/cli/command/ListPatchesCommand.kt
The following patches from [revanced patches v2.195.0](https://github.com/ReVanced/revanced-patches/releases/tag/v2.195.0) have their `compatiblePackages: Set<CompatiblePackage>?` set to `null`:
- Remove screen capture restriction
- Export all activities
- Remove screenshot restriction
- Enable Android debugging
- Override certificate pinning
- Change package name
- Predictive back gesture
- Spoof Wi-Fi connection
which, I assume, means they are universal and not application-specific. So I added an option to list those too when filtering by package name.
=> feat: List patches which are compatible with any app

docs/0_prerequisites.md
It said that an ABI other than ARMv7 is supported, but ARMv8 isn't supported as well
(ReVanced CLI only contains x86 and x86-64 of aapt2)
This PR corrects this
And clarify the way to use a custom AAPT binary
=> docs: List supported ABIs correctly and add a mention how to use other ones

docs/1_usage.md
`-i` is to install the app, it should `-e` to enable the patches
=> docs: Use correct option name in command example

build.gradle.kts
First, exclude aapt1 binaries.
aapt1 is never used in ReVanced CLI, but accounts for 10% of the jar size.
Second, specify `app.revanced:revanced-patcher` explicitly in the minimize block, because revanced-library does not need to be excluded from minimization.
Since ReVanced Library was born, `exclude(dependency("app.revanced:.*"))` has been excluding revanced-library from minimization unintentionally.
(This line exists before ReVanced Library was created.)
I tested patching, list patches, list versions, mount/unmount, and install/uninstall. It worked as expected.
Finally, remove `exclude(dependency("org.jetbrains.kotlin:.*"))` as it has no effect.  Removing or adding this line made no difference.
This PR reduces the jar size as follows:
Removing aapt1: 49.9 MB -> 44.8 MB
Optimize …
=> build: Remove AAPT1 binary & minimize ReVanced Library

src/main/kotlin/app/revanced/cli/command/PatchCommand.kt
- make using `--mount` option in 'patch' command require the inclusion of `-i/--install` option.
- as it stands, if `-i` is not provided, then `--mount` flag is really not toggling the installation and user is left oblivious whether the patched apk is being installed or not
=> fix: Group `mount` and `install` options into an argument group 

.github/workflows/build_pull_request.yml, .github/workflows/release.yml
Why fetch *all* commit history when we are not going to use them.
=> ci: Remove fetch-depth from checkout
